env: "local" # local, dev, prod
private_key: "secretpassword12345"
storage:
  POSTGRES_HOST: "localhost"
  POSTGRES_PORT: 5432
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "authenticationService"
http_server:
  address: "localhost:8080"
